### ISSUE TITLE
502 Bad Gateway - Failed to authenticate HTTPS connection.

### ISSUE THREAD

**Issue by CorrieBarton** [CorrieBarton/SlackAnonymousMessages#7]
Attempting to POST to the api through a tunnelling service such as ngrok is now resulting in 502 being returned. (tried ngrok and serveo)

Output log in VS shows:

```
HttpsConnectionAdapter:Debug: Failed to authenticate HTTPS connection.

System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)

```
Have reverted back to earlier builds, issue still occurs. Spent a few hours looking through google results to no avail. 

If anyone has any idea whats causing it, that would be really helpful.

**Comment by CorrieBarton** [comment]
Caused by HTTPS connection, fixed by using unsecured connection with tunnel service
